### PR TITLE
More like jetbrains

### PR DESCRIPTION
**Pull request by steezeburger**
This PR adds some keybindings to make the jetbrains keybindings more like jetbrains
* cmd-backspace to delete a whole line
* cmd-shift-o to toggle file finder
* cmd-alt-l to format code

### CODE REVIEW

**Comment by JosephTLyons** [comment]
Hey @steezeburger, did this commands now work for you by default?  cmd-backspace should be baked into zed at a lower, and the jetbrains keymap should just be adding stuff on top.  Did you find a place where cmd-backspace didn't work?  Seems to be working on my side.  cmd-shift-o is also working for me and it is defined in the keymap, but it's under a different context than where you added it.  Was it not working in a place where you expected it to work?

**Comment by steezeburger** [comment]
@JosephTLyons they are still just slightly different from Jetbrains.
Without my PR:
`cmd-shift-o` does open the file finder when the cursor is in the editor, but not when you have a file selected from the left sidebar.
`cmd-backspace` only deletes from the cursor to beginning of line, not the whole line like in Jetbrains.

**Comment by JosephTLyons** [comment]
Hey @steezeburger, 

The `mode == <editor_mode>` is how we scope the bindings to certain types of editors.  In Zed, we have:

```rs
pub enum EditorMode {
    SingleLine,
    AutoHeight { max_lines: usize },
    Full,
}
```

`SingleLine` is a single line editor, like when renaming a file
`Full` is like your standard text editor
`AutoHeight` will be used for things in the future

Also, what you wrote makes sense about the differences in Zed and JB - I'm ok with merging this if you are finishing up.

**Comment by steezeburger** [comment]
No worries at all! And thank you for the information about EditorMode. 

I'm happy with this being merged now. I don't have any other keybindings to add for now!

**Pull request merged**
